# This is a basic workflow to help you get started with Actions

name: print_the_date

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
            - run: date
    job2:
        runs-on: macos-latest
        steps:
            - run: date
    job3:
        runs-on: windows-latest
        steps:
            - run: date
    job4:
        needs: job1
        runs-on: windows-latest
        steps:
            - run: date
        
  
